### ISSUE TITLE
No background color in sidebar

### ISSUE THREAD

**Issue by umutbozdag** [dashersw/mogollar#27]
There is no background color in the sidebar. My OS is Windows 10

![no-bg](https://user-images.githubusercontent.com/43722871/91893760-46332900-ec9d-11ea-99a4-aa4b560cb3c4.PNG)

**Comment by dashersw** [comment]
Thank you for the issue @umutbozdag! In macOS, this part is translucent — hence no background image. We should make sure transparency is only for macOS, or on Windows this part should have its own background.
